#!/bin/sh

# Constants
FILES_PATH=files
FILES_HOME_PATH=$FILES_PATH/home
FILES_ETC_PATH=$FILES_PATH/etc

# Aliases
alias cp='cp -vf'
alias mkdir='mkdir -p'

# Clean-up
rm -rf $FILES_PATH

# home
mkdir $FILES_HOME_PATH
cd $FILES_HOME_PATH

cp ~/.bash_profile .
cp ~/.bashrc .
cp ~/.gitconfig .
cp ~/.xinitrc .
cp ~/.Xresources .
cp ~/.asoundrc .

# .emacs.d
mkdir .emacs.d
mkdir .emacs.d/themes
mkdir .emacs.d/langs
cp ~/.emacs.d/init.el .emacs.d
cp ~/.emacs.d/config.org .emacs.d
cp ~/.emacs.d/themes/*.el .emacs.d/themes
cp ~/.emacs.d/langs/*.el .emacs.d/langs
cp ~/.emacs.d/build .emacs.d

# .fonts
mkdir .fonts
cp ~/.fonts/*.ttf .fonts
cp ~/.fonts/*.otf .fonts

# .color-*
cp ~/.color-light .
cp ~/.color-dark .

# PROG
mkdir PROG
cp -r ~/PROG/* PROG

# /etc
cd ../..
mkdir $FILES_ETC_PATH
cd $FILES_ETC_PATH
cp /etc/issue .
cp /etc/motd .
cp /etc/pacman.conf .

# git
git diff
git status
