# -*- mode:sh -*-
alias ls='ls --color=never -lh'
alias l='ls'
alias p='pwd'
alias n='nano'
alias r='sudo protonvpn r'
alias d='sudo protonvpn d'
alias vlcrec='vlc --recursive expand'
alias em='startx 2> /dev/null'
alias feh='feh -B "white"'
