#!/usr/bin/php
<?php
require("my-library.php");

$api = "https://allekok.ir/dev/tools";

$input = $argv[1];
$input = urlencode($input);

$request = "{$api}/search.php?q={$input}";

$response = file_get_contents($request);
$response = json_decode($response, true);

p("========= شاعیران =========");
foreach($response["poets"]["meta"] as $poet) {
	p("\t" .
	  $poet["poet"] .
	  " -> " .
	  "allekok.ir/{$poet["poet_id"]}");
}
foreach($response["poets"]["context"] as $poet) {
	p("\t" .
	  $poet["poet"] .
	  " -> " .
	  "allekok.ir/{$poet["poet_id"]}");
}
foreach($response["poets"]["lastChance"] as $poet) {
	p("\t" .
	  $poet["poet"] .
	  " -> " .
	  "allekok.ir/{$poet["poet_id"]}");
}
p();

p("========= کتێبەکان =========");
foreach($response["books"]["meta"] as $book) {
	p("\t" .
	  $book["poet"] .
	  " / {$book["book"]}" .
	  " -> " .
	  "allekok.ir/{$book["poet_id"]}/{$book["book_id"]}");
}
foreach($response["books"]["context"] as $book) {
	p("\t" .
	  $book["poet"] .
	  " / {$book["book"]}" .
	  " -> " .
	  "allekok.ir/{$book["poet_id"]}/{$book["book_id"]}");
}
foreach($response["books"]["lastChance"] as $book) {
	p("\t" .
	  $book["poet"] .
	  " / {$book["book"]}" .
	  " -> " .
	  "allekok.ir/{$book["poet_id"]}/{$book["book_id"]}");
}
p();

p("========= شیعرەکان =========");
foreach($response["poems"]["firstChance"]["meta"] as $poem) {
	p("\t" .
	  $poem["poet"] .
	  " / {$poem["book"]}" .
	  " / {$poem["poem"]}" .
	  " -> " .
	  "allekok.ir/" .
	  "{$poem["poet_id"]}/{$poem["book_id"]}/{$poem["poem_id"]}");
}
foreach($response["poems"]["firstChance"]["context"] as $poem) {
	p("\t" .
	  $poem["poet"] .
	  " / {$poem["book"]}" .
	  " / {$poem["poem"]}" .
	  " -> " .
	  "allekok.ir/" .
	  "{$poem["poet_id"]}/{$poem["book_id"]}/{$poem["poem_id"]}");
}
foreach($response["poems"]["lastChance"]["meta"] as $poem) {
	p("\t" .
	  $poem["poet"] .
	  " / {$poem["book"]}" .
	  " / {$poem["poem"]}" .
	  " -> " .
	  "allekok.ir/" .
	  "{$poem["poet_id"]}/{$poem["book_id"]}/{$poem["poem_id"]}");
}
foreach($response["poems"]["lastChance"]["context"] as $poem) {
	p("\t" .
	  $poem["poet"] .
	  " / {$poem["book"]}" .
	  " / {$poem["poem"]}" .
	  " -> " .
	  "allekok.ir/" .
	  "{$poem["poet_id"]}/{$poem["book_id"]}/{$poem["poem_id"]}");
}

/*
 * Local Variables:
 * mode: web
 * End:
 */
?>
