#!/usr/bin/php
<?php
require('my-library.php');

$f = nth(1) or die();

$include_path = '/home/alleko/domains/allekok.ir/allekok/tewar-2';
require($include_path . '/config.php');
require($include_path . '/src/backend/library.php');

$lookup = lookup($f, dict_list(), -1);
foreach ($lookup as $point=>$res)
	if(!empty($res)) {
		echo "$point\n";
		foreach($res as $i=>$w)
			echo "\t$w[0]\t$w[1]\n";
	}
/*
 * Local Variables:
 * mode: web
 * End:
 */
?>
