#!/usr/bin/php
<?php
require("my-library.php");

const DEF_BROWSER = "firefox";

$browser = nth_pair("-browser");
$port = nth_pair("-port", "5555");
$path = nth_pair("-path", ".");
$host = "localhost:{$port}";
$browser_command =  !$browser ?
		    DEF_BROWSER . " http://{$host}/" :
		    "{$browser} http://{$host}/";
exec("cd {$path} && php -S {$host} & {$browser_command}");

/*
 * Local Variables:
 * mode: web
 * End:
 */
?>
