#!/usr/bin/php
<?php
require('my-library.php');

$f = nth(1) or die();

$include_path = realpath(__DIR__ . '/..') . '/projects/tewar-2';
require($include_path . '/config.php');
require($include_path . '/src/backend/library.php');

$lookup = lookup(match_words($f), dict_list());
foreach ($lookup as $dict=>$res)
{
    if(!empty_rec($res))
    {
	echo "$dict\n";
	foreach($res as $w=>$m)
	{
	    if($m) echo "\t$w\t$m\n";
	}
    }
}

function empty_rec ($arr=[])
{
    foreach($arr as $o)
    {
	if($o) return false;
    }
    return true;
}
?>
